config/routes.rb
Rails.application.routes.draw do
  root                    'static_pages#home'
  get      'signup'    => 'users#new'
  get      'login'     => 'sessions#new'
  post     'login'     => 'sessions#create'
  delete   'logout'    => 'sessions#destroy'
  
  resources :mail, only: [:new, :create]
  resources :users, only: [:create, :show]
  
  resources :jobs do
    collection { post :import }
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  require 'csv'
  
  validates :user_id, :title, :email, presence: true
  validates :sent, :inclusion => {:in => [true, false]}
  # before_validation :sent_false
  before_validation :process_address
  
  belongs_to :user
  
  #
  # def sent_false
  #   self.sent = false
  # end
  
  def self.import(file, user)
      CSV.foreach(file.path, encoding: "r:ISO-8859-1", headers: true) do |row|
      next if row["company"].nil?
      row = row.to_hash
      j = user.jobs.new(row)
      j.sent = false
      j.save!
    end
  end
  
  def process_greeting    
    return "Dear #{self.company} team," if self.recipient.nil?
    return "Dear #{recipient},"
  end
  
  def process_address
    if (self.address) && (self.sent == false)
      parsed_address = GoogleMapsGeocoder.new(self.address)
      self.address = parsed_address.formatted_address
      self.street_address = parsed_address.formatted_street_address
      self.location = parsed_address.city + " " + parsed_address.state_short_name
      self.postal_code = parsed_address.postal_code
    end
  end
  
  def process_title
    return "#{self.title} -- #{self.location}" if self.location
    self.title
  end
  
  def parse_address
  end
  
  def send_job
    self.sent = true
    self.save!
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, :resume, presence: true
  validates :password, length: { minimum: 6 }, confirmation: true, on: :create
  after_initialize :give_session_token
  has_secure_password
  attr_accessor :resume
  
  mount_uploader :resume, ResumeUploader
  
  has_many :jobs
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  protected
  
    def give_session_token
      self.session_token ||= SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  def log_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end
  
  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by(session_token: session[:token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def redirect_if_logged_in
    redirect_to jobs_url if logged_in?
  end
  
  def redirect_unless_logged_in
    redirect_to root_path unless logged_in?
  end
  
  def log_out!
    current_user.reset_session_token!
    session[:token] = nil
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :redirect_unless_logged_in
  
  include ActionView::Helpers::DateHelper
  before_action :all_jobs, only: [:index, :destroy]
  respond_to :html, :js
  
  def new
    @job = Job.new
  end
  
  def create
    @job = current_user.jobs.new(job_params)
    debugger
    @job.save!
  end
  
  def show
    @user = current_user
    @job = Job.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do 
        render :pdf => "jobs/show.pdf.erb"
      end
    end
  end
  
  def destroy
    job = Job.find(params[:id])
    job.destroy
  end
  
  def import
    Job.import(params[:file], current_user)
    flash[:success] = "Jobs Imported"
    redirect_to jobs_url
  end
  
  protected
  
  def all_jobs
    @jobs = current_user.jobs
  end
  
  def job_params
    params.require(:job).permit(:company, :recipient, :address, :blurb, :email,)
  end
end

app/controllers/mail_controller.rb
class MailController < ApplicationController
  def new
    
  end
  
  def create
    current_user.jobs.each do |job|
      next if job.sent == true
      @job = job
      @user = current_user
      resume = File.read(current_user.resume.current_path)
      pdf = render_to_string(:pdf => 'cover_letter',:template => 'jobs/show.pdf.erb')
      UserMailer.email_blast(job, pdf, resume, {user_name: params[:gmail][:user_name], password: params[:gmail][:password]}).deliver_now
      job.send_job
    end
    redirect_to jobs_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new]
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user # user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to jobs_path
    else
      flash.now[:danger] = "Invalid email/password confirmation"
      render 'new'
    end
  end
  
  def destroy
    log_out!
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :redirect_if_logged_in
  
  def home
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user_validation, only: [:show]
  before_action :redirect_if_logged_in, only: [:new]
  before_action :redirect_unless_logged_in, only: [:show]
  
  include UsersHelper
  
  def new
    @user = User.new
  end
  
  def create 
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to jobs_path
    else
      flash.now[:danger] = @user.errors.full_messages
      render 'new'
    end
  end
  
  def show
    if params[:id] == current_user.id.to_s
      @user = User.find(params[:id])
      render :show
    else
      redirect_to new_session_url
    end
  end
  
  protected
  
    def user_params
      params.require(:user).permit(:email, :signature, :password, :password_confirmation, :resume)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper  
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/mail_helper.rb
module MailHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def correct_user_validation
	  unless params[:id] == current_user.id.to_s
      redirect_to login_url
    end
  end
  
end

app/views/jobs/_form.html.erb
<tr>
	<%= form_for @job, remote: true do |f| %>
	<th scope="row" class="col-id">	<%= f.submit "+", class: 'btn btn-sm btn-success sign-in-btn'%></th>
  <td style="" class="col-company"><%= f.text_field :company, class: "form-control col-company" %></td>
  <td style="" class="col-blurb"><%= f.text_field :blurb, class: "form-control"%></td>
	<td style="" class="col-recipient"><%= f.text_field :recipient, class: "form-control" %></td>	
	<td style="" class="col-title"><%= f.text_field :title, class: "form-control" %></td>	
	<td style="" class="col-address"><%= f.text_field :address, class: "form-control" %></td>	
  <td style="" class="col-blurb"><%= f.text_field :blurb, class: "form-control" %></td>
	<td style="" class="col-email"><%= f.text_field :email, class: "form-control" %></td>
	<td style=""></td>
	<% end %>
</tr>

app/views/jobs/_jobs.html.erb
<h3>Jobs</h3>

<table class="table table-hover" style="table-layout:fixed">
	<caption>Jobs In Loading Area</caption>
	<thead>
		<tr>
		
			<th scope="col" class="theader col-id">cl</th>
		
			<th scope="col" class="theader col-company">company</th>
		
			<th scope="col" class="theader col-recipient">recipient</th>
		
			<th scope="col" class="theader col-title">title</th>
			
			<th scope="col" class="theader col-address">address</th>
			
			<th scope="col" class="theader col-blurb">blurb</th>
		
			<th scope="col" class="theader col-email">email</th>
		
			<th scope="col" class="theader col-created-at">created</th>
			
			<th scope="col" class="theader col-delete">del</th>
		
		</tr>
	</thead>

	<tbody>
		<% @jobs.each_with_index do |job, idx| %>
			<% next if job.sent == true %>
			<tr>
				<th scope="row"><%= link_to job.id, "jobs/#{job.id}.pdf" %></td>
			  <td style=""><%= job.company %></td>
			  <td style=""><%= job.recipient || "–" %></td>
				<td style=""><%= job.title || "–" %></td>	
				<td style=""><%= job.address || "–" %></td>	
				<td style=""><%= job.blurb || "–" %></td>	
			  <td style=""><%= job.email %></td>
				<td style=""><%= time_ago_in_words(job.created_at) + " ago" %></td>
				<td style="">
						<form action="/jobs/<%= job.id %>" method="POST" data-remote="true">
							<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
						  <input type="hidden" name="_method" value="DELETE">
							<input type="submit" value="x" class="btn btn-danger">
						</form>
				</td>
			</tr>
	  <% end %>



		<tr id="job-form" style="display:none;">
		</tr>
	</tbody>
</table>

<%= link_to 'Add Job', new_job_path, remote: true %>

<!-- Async Job Form -->



<table class="table table-hover" style="table-layout:fixed">
	<caption>Sent Jobs</caption>
	<thead>
		<tr>
		
			<th scope="col" class="theader col-id">cl</th>
		
			<th scope="col" class="theader">company</th>
		
			<th scope="col" class="theader">recipient</th>
		
			<th scope="col" class="theader">blurb</th>
		
			<th scope="col" class="theader">email</th>
		
			<th scope="col" class="theader">sent</th>
			
			<th scope="col" class="theader col-delete">del</th>
		
		</tr>
	</thead>
	
	<tbody>
		<% @jobs.each_with_index do |job, idx| %>
			<% next if job.sent == false %>
			<tr>
				<th scope="row"><%= link_to job.id, "jobs/#{job.id}.pdf" %></td>
			  <td style=""><%= job.company %></td>
			  <td style=""><%= job.recipient || "–" %></td>
				<td style=""><%= job.blurb || "–" %></td>	
			  <td style=""><%= job.email %></td>
				<td style=""><%= time_ago_in_words(job.updated_at) + " ago" %>
				<td style="">
						<form action="/jobs/<%= job.id %>" method="POST" data-remote="true">
							<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
						  <input type="hidden" name="_method" value="DELETE">
							<input type="submit" value="x" class="btn btn-danger">
						</form>
				</td>
			</tr>
	  <% end %>
	</tbody>
</table>

app/views/jobs/destroy.js.erb
$('#jobs').html("<%= j (render 'jobs') %>")

app/views/jobs/index.html.erb
	
	<div class="header-step-container">
		<h3>Download the CSV</h3>
	
	</div>
	<div class="header-step-container">

		<h3>Import a CSV</h3>
			<%= form_tag import_jobs_path,  multipart: true do %>
				<div class="file-upload"><%= file_field_tag :file %></div>
				<div class="file-upload"><%= submit_tag "Import Jobs CSV", class: "btn btn-primary btn-import" %></div>
			<% end %>
	</div>
	<div class="header-step-container">
		<h3>Send Jobs</h3>

		<form accept-charset="UTF-8" action="/mail" method="post">
		  <input name="utf8" type="hidden" value="&#x2713;" />
		  <input name="authenticity_token" type="hidden" value="J7CBxfHalt49OSHp27hblqK20c9PgwJ108nDHX/8Cts=" />
	
			<input name=gmail[user_name] 
						 type="email" 
						 class="form-control form-email-blast top"
						 placeholder="gmail username">
			<input name=gmail[password] 
						 type="password" 
						 class="form-control form-email-blast bottom"
						 placeholder="gmail password">
		 	<button to="submit" 
							class="btn btn-success form-email-blast">
							Send All Jobs
			</button>
		</form>
	</div>
	
<div id="jobs">
	<%= render 'jobs' %>
</div>

app/views/jobs/new.js.erb
$('#job-form').html("<%= j (render 'form') %>");
$('#job-form').slideDown(350);

app/views/jobs/show.pdf.erb
 <meta http-equiv="content-type" content="text/html; charset=utf-8" />
 <%= wicked_pdf_stylesheet_link_tag "jobs" %>
 
<div class="job">
	<body>
		<div class="boxes">
			<div class="box yellow"></div>
			<div class="box red"></div>
			<div class="box blue"></div>
		</div>
		<br>
		<h2><%= @user.signature %></h2>
		<p class="header">770-312-9877 										&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.email %> 										&nbsp;&nbsp;&nbsp;&nbsp;1061 Market Street San Francisco, CA 94103</p>
		
	<div class="cover-paragraphs">
		
		<br>
		<br>
		January 5, 2015
		<br>
		<br>
		<% if @job.recipient %>
			<%= @job.recipient %> 
			<br>
		<% end %>
		<%= @job.company %> 
		<br>
		<%= @job.street_address %>
		<br>
		<%= @job.location %> <%= @job.postal_code %>
		<br>
		<br>
		<%= @job.process_greeting %>
		<br>
			
		<p>
		I am a software developer with experience in Rails, SQL, and Backbone.js. I have a passion for building cool stuff – In my spare time I have developed web applications and games in Javascript as well as Ruby. Recently, I created a home-rental site in an effort to solidify my skills with Backbone.js, and I am currently working on a web- based storyboarding application.
		</p>
		<p>
		I work well in a team-driven environment. While learning to program, I spent countless hours pair programming, and my ability to collaborate and communicate efficiently were essential to my success. Working in a fast-paced, team-oriented, environment where I can work with the best in the industry is important to me. <%= @job.blurb %>
		</p>
		<p>
		Attached, you will find my resume that links to my recent work along with my Github. Thank you for considering my application.
		</p>
		<br>
		<%= @user.signature %>
	<div>
		
	</body>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CVMailer", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", "#" %></li>
				<% if logged_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Jobs", jobs_url %></li>
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", "#" %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Log out", logout_path, method: "delete" %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Log in", login_path %></li>
				<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CvMailer</title>
	<link href='http://fonts.googleapis.com/css?family=Muli:300,400' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<%= render "layouts/header" %>

		<div class="container main-body">
			<% flash.each do |message_type, message| %>
			  <div class="alert alert-<%= message_type %>"><%= message %></div>
			<% end %>
			
			<%= yield %>
		</div>
		
</body>
</html>

app/views/static_pages/home.html.erb
<div class="jumbotron">
	 <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Sign Up</h1>
		<%= form_for @user, :html => { multipart: true } do |f| %>
			<%= f.label :email %>
			<%= f.email_field :email, class: "form-control" %>
		
			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>
		
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: "form-control" %>
			
			<%= f.label :resume, "Resume" %>
			<%= f.file_field :resume %>
			
			<%= f.submit "Create my account", class: 'btn btn-primary sign-in-btn'%>
		
		<% end %>
		<p>Already a user? <%= link_to "Log in here", login_path %></p>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<p>This is the users page and is where the job data will reside</p>